wip: split test and results for easier reading

diff --git a/.github/workflows/npm_release.yml b/.github/workflows/npm_release.yml
--- a/.github/workflows/npm_release.yml
+++ b/.github/workflows/npm_release.yml
@@ -94,9 +94,18 @@ jobs:
           npm install -g @edusperoni/junit-cli-report-viewer verify-junit-xml
       - name: Prepare
         run: npm run setup-ci
-      - name: Test
+      - name: Xcode Tests
+        uses: nick-fields/retry@v2
+        # try to run the tests with xcpretty. If it fails then try again without xcpretty twice for better log output
+        # the xcode tests are a bit flaky and they should never fail on this step, as this step only collects the JS test results as junit xml
+        with:
+          timeout_minutes: 20
+          max_attempts: 3
+          command: set -o pipefail && xcodebuild -project v8ios.xcodeproj -scheme TestRunner -resultBundlePath $HOME/test_results -destination platform\=iOS\ Simulator,OS\=16.2,name\=iPhone\ 14\ Pro\ Max build test | xcpretty
+          on_retry_command: rm -rf $HOME/test_results*
+          new_command_on_retry: xcodebuild -project v8ios.xcodeproj -scheme TestRunner -resultBundlePath $HOME/test_results -destination platform\=iOS\ Simulator,OS\=16.2,name\=iPhone\ 14\ Pro\ Max build test
+      - name: Validate Test Results
         run: |
-          xcodebuild -project v8ios.xcodeproj -scheme TestRunner -resultBundlePath $HOME/test_results -destination platform\=iOS\ Simulator,OS\=16.2,name\=iPhone\ 14\ Pro\ Max build test
           xcparse attachments $HOME/test_results.xcresult $HOME/test-out
           find $HOME/test-out -name "*junit*.xml" -maxdepth 1 -print0 | xargs -n 1 -0 npx junit-cli-report-viewer
           find $HOME/test-out -name "*junit*.xml" -maxdepth 1 -print0 | xargs -n 1 -0 npx verify-junit-xml
